services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  mongo:
    image: mongo:4.4.30
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: unless-stopped
    env_file:
      - ./docker/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - backend_uploads:/app/uploads
    ports:
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  redis_data:
  mongo_data:
  backend_uploads:

